# Instala Alpine preparado com o Node.js
FROM node:alpine

# Cria o diretório /app e copia o conteúdo do projeto para dentro dele
COPY . /app

# Define o diretório de trabalho como /app e o comando para iniciar a aplicação
WORKDIR /app
CMD node app.js